version: '3'
services:
  app:
    image: nginx:alpine
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
#      - "./docker/ssl:/etc/ssl"
      - "./app:/var/www/html"
      - "./docker/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "8000:80"
      - "3000:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
      - mysqldb
    networks:
      - test
  php:
    image: nanoninja/php-fpm:${PHP_VERSION}
    restart: always
    volumes:
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./app:/var/www/html"
    networks:
      - test
  composer:
    image: "composer"
    volumes:
      - "./app:/app"
    command: install
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
      - mysqldb
    networks:
      - test
  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - test
networks:
  test:
volumes:
  db_data: